// source: https://www.touropia.com/best-countries-to-visit-in-asia/

export const DATA = {
  imgIndonesia: "https://www.touropia.com/gfx/b/2020/01/indonesia.jpg",
  imgIndia: "https://www.touropia.com/gfx/b/2020/01/india.jpg",
  imgJapan: "https://www.touropia.com/gfx/b/2020/01/japan.jpg",
  imgThailand: "https://www.touropia.com/gfx/b/2020/01/thailand.jpg",
  imgChina: "https://www.touropia.com/gfx/b/2020/01/china.jpg",
  articleIndonesia: "Made up of more than 18,000 islands that span some 4,700 kilometers from east to west, Indonesia covers a huge area. As such, the nation is one of the most diverse places on Earth – whether that’s in terms of people, culture, and languages or landscapes and wildlife.\n\n In many ways, the archipelago defies definition. For instance, its small, secluded sleepy settlements are in stark contrast to the teeming and chaotic capital of Jakarta. One of the most populous nations in the world, its customs, traditions, and cuisines also vary dramatically depending on where you go.\n\n Lying between the Indian and Pacific Oceans, its islands’ habitats are just as diverse. While in Bali you can find beautiful beaches, Borneo has wonderful wildlife and awe-inspiring orangutans. With so much to see and do, the ‘Emerald of the Equator’ definitely warrants a visit.",
  articleIndia: "Home to one of the world’s richest and oldest civilizations, India is awash with different cultures, religions, peoples, and traditions. It is this diversity that makes it so mesmerizing to explore. \n\n While the Himalayas dominate the north, steamy jungle, picturesque tea plantations, and gorgeous beaches can be found in the rest of the country. Tucked away among these varied landscapes are millennia-old archaeological sites and colorful yet chaotic cities such as Mumbai and New Delhi. \n\n From temples to cuisine and history to wildlife, the world’s second-most populous country has something for everyone. The only question is where to begin.",
  articleJapan: "Although it consists of almost 7,000 islands, most of Japan’s main sights and tourist attractions can be found on Hokkaido, Honshu, Kyushu, and Shikoku. These are the four largest of them. \n\n Lying to the east of mainland Asia, the island nation is a fascinating place as old and new collide wherever you go. While the futuristic metropolises of Tokyo and Yokohama are full of skyscrapers and neon lights, Kyoto and Nara instead boast traditional palaces and age-old temples.\n\n Covered in mountains and forests, the country is also home to some delightful nature and scenery. This explains why the vast majority of its large population is found in the densely populated cities that hug its long and indented coastline.",
  articleThailand: "Thanks to its breathtaking beaches, glittering temples, and welcoming population, Thailand is a very popular tourist destination. Fittingly enough, it is often called ‘the Land of Smiles.’\n\n While Bangkok has lots of fantastic cuisine and nightlife on offer, Chiang Mai and Chiang Rai are home to some of the nation’s most famous temples. Further afield, you can find wild jungle, picturesque paddy fields, and quiet and secluded towns and villages.\n\n Lying in between the Andaman Sea and the Gulf of Thailand, its golden sands and underwater marvels attract hordes of people every year. Many also come to party in its beachside towns, visit idyllic islands such as Ko Tao, or enjoy the stunning scenery at Krabi.",
  articleChina: "Dominating Asia in terms of both its size and population, China boasts one of the world’s oldest civilizations. As such, incredible historical and cultural landmarks are on show wherever you go.\n\n While the Great Wall of China is obviously its main attraction, the Terracotta Army in Xi-an and the Forbidden City in Beijing attract just as many people. Others come to enjoy China’s beautiful scenery that includes towering mountains, endless rice terraces, and the desolate Gobi Desert.\n\n The most populous nation on Earth, China is home to many rapidly modernizing cities that are enthralling to visit. Its age-old traditions and customs remain, however. A continent of a country, China and its vast and varied landscapes, cities, and cultures could take a lifetime to explore.",
  videoCountries: "https://www.youtube.com/embed/UWKhvzdnctY"
}